<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tb_materi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_materi_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('tb_materi/tb_materi_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tb_materi_model->json();
    }

    public function read($id) 
    {
        $row = $this->Tb_materi_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'date' => $row->date,
		'judul' => $row->judul,
		'caption' => $row->caption,
		'path_sambutan' => $row->path_sambutan,
	    );
            $this->load->view('tb_materi/tb_materi_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tb_materi'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('tb_materi/create_action'),
	    'id' => set_value('id'),
	    'date' => set_value('date'),
	    'judul' => set_value('judul'),
	    'caption' => set_value('caption'),
	    'path_sambutan' => set_value('path_sambutan'),
	);
        $this->load->view('tb_materi/tb_materi_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'date' => $this->input->post('date',TRUE),
		'judul' => $this->input->post('judul',TRUE),
		'caption' => $this->input->post('caption',TRUE),
		'path_sambutan' => $this->input->post('path_sambutan',TRUE),
	    );

            $this->Tb_materi_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('tb_materi'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tb_materi_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('tb_materi/update_action'),
		'id' => set_value('id', $row->id),
		'date' => set_value('date', $row->date),
		'judul' => set_value('judul', $row->judul),
		'caption' => set_value('caption', $row->caption),
		'path_sambutan' => set_value('path_sambutan', $row->path_sambutan),
	    );
            $this->load->view('tb_materi/tb_materi_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tb_materi'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'date' => $this->input->post('date',TRUE),
		'judul' => $this->input->post('judul',TRUE),
		'caption' => $this->input->post('caption',TRUE),
		'path_sambutan' => $this->input->post('path_sambutan',TRUE),
	    );

            $this->Tb_materi_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('tb_materi'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tb_materi_model->get_by_id($id);

        if ($row) {
            $this->Tb_materi_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('tb_materi'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tb_materi'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('date', 'date', 'trim|required');
	$this->form_validation->set_rules('judul', 'judul', 'trim|required');
	$this->form_validation->set_rules('caption', 'caption', 'trim|required');
	$this->form_validation->set_rules('path_sambutan', 'path sambutan', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Tb_materi.php */
/* Location: ./application/controllers/Tb_materi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-18 15:15:25 */
/* http://harviacode.com */