<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tb_kelola_jadwal_model extends CI_Model
{

    public $table = 'tb_kelola_jadwal';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,jam_bimbingan,jumlah_siswa,hari_bimbingan,mata_pelajaran');
        $this->datatables->from('tb_kelola_jadwal');
        //add this line for join
        //$this->datatables->join('table2', 'tb_kelola_jadwal.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('tb_kelola_jadwal/read/$1'),'Read')." | ".anchor(site_url('tb_kelola_jadwal/update/$1'),'Update')." | ".anchor(site_url('tb_kelola_jadwal/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('jam_bimbingan', $q);
	$this->db->or_like('jumlah_siswa', $q);
	$this->db->or_like('hari_bimbingan', $q);
	$this->db->or_like('mata_pelajaran', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('jam_bimbingan', $q);
	$this->db->or_like('jumlah_siswa', $q);
	$this->db->or_like('hari_bimbingan', $q);
	$this->db->or_like('mata_pelajaran', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tb_kelola_jadwal_model.php */
/* Location: ./application/models/Tb_kelola_jadwal_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-18 15:15:25 */
/* http://harviacode.com */